local_rank: 0
version: "/root/autodl-tmp/LLMQuant-Learning/Code/LISA/weights/LISA_PLUS_7B"
precision: "bf16"
image_size: 1024
model_max_length: 1024
lora_r: 8
vision_tower: "/root/autodl-tmp/.cache/huggingface/transformers/models--openai--clip-vit-large-patch14-336/snapshots/ce19dc912ca5cd21c8a653c79e251e808ccabcd1"
quant_method: "gptq"
quant_config: "quant/gptq.yaml"
exp_name: "LISA_PLUS_7B_gptq_ReasonSeg_val"
report_path: "/root/autodl-tmp/LLMQuant-Learning/Code/LISA/results/LISA_PLUS_7B_gptq_ReasonSeg_val.md"

dataset_dir: "/root/autodl-tmp/LLMQuant-Learning/Code/LISA/dataset"
test_dataset: "ReasonSeg|val"
workers: 4
batch_size: 1

lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: "q_proj,v_proj"

ce_loss_weight: 1.0
dice_loss_weight: 0.5
bce_loss_weight: 2.0

vision_pretrained: "/root/autodl-tmp/LLMQuant-Learning/Code/LISA/weights/SAM/sam_vit_h_4b8939.pth"
out_dim: 256
resume: ""

train_mask_decoder: true
use_mm_start_end: false
conv_type: "llava_v1"
