local_rank: 0
version: "/root/autodl-tmp/LISA/weights/LISA_PLUS_7B"
vis_save_path: "./vis_output"
precision: "bf16"
image_size: 1024
model_max_length: 1024
lora_r: 8
vision_tower: "/root/autodl-tmp/.cache/huggingface/transformers/models--openai--clip-vit-large-patch14-336/snapshots/ce19dc912ca5cd21c8a653c79e251e808ccabcd1"
load_in_8bit: false
load_in_4bit: false

dataset: "reason_seg"
sample_rates: "1"
sem_seg_data: "ade20k"
refer_seg_data: "refclef"
vqa_data: "llava_instruct_150k"
reason_seg_data: "ReasonSeg|train"
val_dataset: "ReasonSeg|val"
dataset_dir: "/root/autodl-tmp/LISA/dataset"

log_base_dir: "/root/autodl-tmp/LLMQuant-Learning/Code/LISA/runs"
exp_name: "reasonseg_train239_336_10ep_500step_bs5"
epochs: 10
steps_per_epoch: 500
batch_size: 1
grad_accumulation_steps: 1
val_batch_size: 1
workers: 2
lr: 0.0003

ce_loss_weight: 1.0
dice_loss_weight: 0.5
bce_loss_weight: 2.0

lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: "q_proj,v_proj"

explanatory: 0.1
beta1: 0.9
beta2: 0.95
num_classes_per_sample: 3
exclude_val: false
no_eval: false

vision_pretrained: "/root/autodl-tmp/LISA/weights/SAM/sam_vit_h_4b8939.pth"
out_dim: 256
resume: ""
print_freq: 20
start_epoch: 0
gradient_checkpointing: true
train_mask_decoder: true
use_mm_start_end: false
auto_resume: false
conv_type: "llava_v1"
